name: Run Bash Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts


    steps:
      - name: Checkout out the repository to the runner
        uses: actions/checkout@v4

      - name: Run the script
        run: |
          chmod u+x ./myscript.sh
          ./myscript.sh