name: Jozefs test

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of employee
        required: true
        type: string

jobs:
  Jozefs test:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings from GitHuba Action
        run: echo "Hello ${{ inputs.name }}"

