name: Artifact Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        exit: 1

      - name: Create build file
        run: echo "Build artifact content" > build.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.txt
          retention-days: 1
            # Valid values:
            # Minimum: 1
            # Maximum: 90 (for public repos) or 400 (for private repos with GitHub Enterprise)

  use-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Show file content
        run: cat build.txt
