name: mytest

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of employee
        required: true
        type: string

jobs:
  mytest:
    runs-on: ubuntu-latest
    steps:

      - name: Dump GitHub context
        run: echo '${{ toJson(github) }}'

      - name: GitHub Action
        run: echo "$MY_ACTOR"
        env:
          MY_ACTOR: ${{ github.actor }}

      - name: Greetings from GitHub Action
        run: echo "Hello ${{ inputs.name }}"

