name: mytest

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of employee
        required: true
        type: string

jobs:
  mytest:
    runs-on: ubuntu-latest
    steps:

      - name: GitHuba Action
        run: echo "$MY_ACTION"
        env:
          MY_ACTION: ${{ github.action }}

      - name: Greetings from GitHub Action
        run: echo "Hello ${{ inputs.name }}"

