name: scheduler - every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  hello_world:
    # if: github.event.schedule
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
